### ISSUE TITLE
Dom can log into the APP

### ISSUE THREAD

**Issue by deanachou** [unicornTDD/greenfield-my-basket-diaries#15]
Given the login page is visible
When Dom inputs his email and password
Then he will be successfully redirected to the dashboard

**Comment by deanachou** [comment]
If email doesn't exist, throw an error

if email does exist but password is incorrect, throw error

**Comment by DepartureLV** [comment]
In development, this feature is already done. Users can now log in and see the dashboard.
On Production, somehow it's not working, we need to investigate further.
